name: Workflow Demo

on: push

jobs:
  build-job1:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create a text file
      run: echo "Hello, world!" > hello.txt

    - name: Archive text file
      uses: actions/upload-artifact@v4
      with:
        name: hello-artifact
        path: hello.txt

 download-job: 
   needs: build-job1
   runs-on: ubuntu-latest

   steps:
   - name: Download text File from Bhuild Job
     uses: actions/download-artifact@v3
     with:
       name: Read Hello txt file
       run: ./artifacts

   - name: Read Hello txt file   
     run: cat ./artifacts/hello.txt
